name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.HOST_DNS }}
          EC2_USER: ${{ secrets.USERNAME }}
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_PORT: ${{ secrets.EC2_PORT }}
        run: |
          echo "${EC2_KEY}" > server.pem
          chmod 600 server.pem
          ssh -o StrictHostKeyChecking=no -i server.pem -p ${EC2_PORT:-22} ${EC2_USER}@${EC2_HOST} 'bash -s' << 'EOF'
            cd /path/to/your/app
            git pull origin main
            node index.js
          EOF
        continue-on-error: true

      - name: Cleanup
        run: rm -f server.pem
